name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test vettore
      id: test-vettore
      uses: education/autograding-command-grader@v1
      with:
        test-name: test vettore
        setup-command: ''
        command: make test
        timeout: 10
    - name: test vettore vuoto
      id: test-vettore-vuoto
      uses: education/autograding-command-grader@v1
      with:
        test-name: test vettore vuoto
        setup-command: ''
        command: make test_vuoto
        timeout: 10
    - name: test vettore 10 elementi
      id: test-vettore-10-elementi
      uses: education/autograding-command-grader@v1
      with:
        test-name: test vettore 10 elementi
        setup-command: ''
        command: make test_10_elementi
        timeout: 10
    - name: test vettore maggiore 10 elementi
      id: test-vettore-maggiore-10-elementi
      uses: education/autograding-command-grader@v1
      with:
        test-name: test vettore maggiore 10 elementi
        setup-command: ''
        command: make test_11_elementi
        timeout: 10
    - name: test vettore con elementi doppi
      id: test-vettore-con-elementi-doppi
      uses: education/autograding-command-grader@v1
      with:
        test-name: test vettore con elementi doppi
        setup-command: ''
        command: make test_elementi_doppi
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-VETTORE_RESULTS: "${{steps.test-vettore.outputs.result}}"
        TEST-VETTORE-VUOTO_RESULTS: "${{steps.test-vettore-vuoto.outputs.result}}"
        TEST-VETTORE-10-ELEMENTI_RESULTS: "${{steps.test-vettore-10-elementi.outputs.result}}"
        TEST-VETTORE-MAGGIORE-10-ELEMENTI_RESULTS: "${{steps.test-vettore-maggiore-10-elementi.outputs.result}}"
        TEST-VETTORE-CON-ELEMENTI-DOPPI_RESULTS: "${{steps.test-vettore-con-elementi-doppi.outputs.result}}"
      with:
        runners: test-vettore,test-vettore-vuoto,test-vettore-10-elementi,test-vettore-maggiore-10-elementi,test-vettore-con-elementi-doppi
